---
- hosts: all
  sudo: true
  user: vagrant
  vars:
    mysql_root_pw : "root"
  tasks:
    - name: set mysql repository
      yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present
    - name: install apache
      yum: name=httpd state=latest
    - name: install php
      yum: name={{item}} state=present
      with_items:
        - php
        - php-devel
        - php-fpm
        - php-mbstring
      notify:
        - restart apache
    - name: apache restart
      action: service name=httpd state=started
    - name: install mysql
      yum: name={{item}} enablerepo=mysql56-community state=present
      with_items:
        - mysql-community-server
      notify:
        - restart mysql
    - name: mysql restart
      action: service name=mysqld state=started
  handlers:
    - name: restart apache
      action: service name=httpd state=restarted enabled=yes
    - name: restart mysql
      action: service name=mysqld state=restarted enabled=yes
